name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  integration:
    name: Continous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code
        run: echo "Linting Repository"

      - name: Run unit test cases
        run: echo "Running unit test cases"

  build-and-push-ecr-image:
    name: Continous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        run: |
          docker build -t networksecurity .

      - name: Tag Image
        run: |
          docker tag networksecurity:latest public.ecr.aws/f2p2m9d3/networksecurity:latest

      - name: Push Image
        run: |
          docker push public.ecr.aws/f2p2m9d3/networksecurity:latest
  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: |
          docker pull public.ecr.aws/f2p2m9d3/networksecurity:latest

      - name: Stop old container
        run: |
          docker stop networksecurity || true
          docker rm networksecurity || true

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name networksecurity public.ecr.aws/f2p2m9d3/networksecurity:latest

      - name: Cleanup unused images
        run: |
          docker system prune -f